# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
timezone: Asia/Tehran
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ""
url: https://bineshafza.ir

# Website info
title: بینش‌افزا
description: مرکز تخصصی آمادگی برای آزمون‌های بین المللی و دوره‌های خاص مکالمه
cover: /assets/images/site-header.jpg
logo: /assets/images/blog-icon.png
logo_dark: /assets/images/favicon.png
favicon: /assets/images/favicon.png
production_url: https://bineshafza.github.io/
source_url: https://github.com/bineshafza/bineshafza.github.io/
CNAME: bineshafza.ir

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: tryghost # replace by your username
facebook: ghost # replace by your username
telegram: bineshafzalanguageinst
instagram: binesh_afza
linkedin: bineshafza

# Disqus
disqus: False
disqus_shortname: username # replace with your disqus username

# Google Analytics
google_analytics: "" # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-jalali]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: bineshafza
repo: bineshafza.github.io
branch: dev
#relative_source: ../fa/
destination: _site
port: 4002

exclude:
  - archive
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*

defaults:
  # News
  - scope:
      path: "_posts/news"
      type: posts
    values:
      class: post-template
      navigation: True
      layout: post
      current: post
      permalink: /news/:title
      category: news
      catname: اخبار
  # Blog
  - scope:
      path: "_posts/blog"
      type: posts
    values:
      class: post-template
      navigation: True
      layout: post
      current: post
      permalink: /blog/:title
      category: blog
      catname: وبلاگ
  # Courses
  - scope:
      path: "_posts/courses"
      type: posts
    values:
      class: post-template
      navigation: True
      layout: post
      current: post
      permalink: /courses/:title
      category: courses
      catname: کلاس‌ها
  # Podcasts
  - scope:
      path: "_posts/podcasts"
      type: posts
    values:
      class: post-template
      navigation: True
      layout: post
      current: post
      permalink: /podcasts/:title
      category: podcasts
      catname: پادکست‌ها
  # Articles
  - scope:
      path: "_posts/articles"
      type: posts
    values:
      class: post-template
      navigation: True
      layout: post
      current: post
      permalink: /articles/:title
      category: articles
      catname: مقالات
  #Multimedia
  - scope:
      path: "_posts/multimedia"
      type: posts
    values:
     class: post-template
     navigation: True
     layout: post
     current: post
     permalink: /multimedia/:title
     category: multimedia
     catname: چند‌رسانه‌ای


image_optim:
  archive_dir: "archive/files/"
  cache_file: "archive/_image_optim_cache.yml"
  image_glob: "assets/images/**/**.{gif,png,jpg,jpeg}"