---
label: Post
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: cover
  label: cover
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: bineshafza
pages:
- _posts/courses/2019-01-10-french-language.md
- _posts/articles/Misc./the-lessons-of-nature.md
- _posts/news/2019-01-19-ماک-آیلتس.md
- _posts/multimedia/quotes/2019-01-14-quote-of-the-day.md
- _posts/multimedia/quotes/2019-01-22-quote-of-the-day.md
- _posts/articles/Misc./why-we-re-all-messed-up-by-our-childhoods.md
